server:
  port: 10000
spring:
  application:
    name: gulimall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.230:3306/gulimall_pms?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 999f941b-0bbf-4574-b1f9-e24ff6e341ab
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
logging:
  level:
    top.codecrab.gulimall: debug
