server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 999f941b-0bbf-4574-b1f9-e24ff6e341ab
logging:
  level:
    top.codecrab.gulimall: debug
