server:
  port: 13000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 999f941b-0bbf-4574-b1f9-e24ff6e341ab
  redis:
    host: 192.168.66.230
    port: 6379
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
